import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

// Montserrat: closest free stand-in for Gotham, the Roblox (2016-18) typeface.
const rbxFont = Montserrat({
  variable: "--font-rbx",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Yumchi's Portfolio",
  description: "Generated by same app and hosted by netlify.",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${rbxFont.variable}`} suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}
